apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: developement
namePrefix: dev-
images:
- name: nginxdemos/hello
  newTag: lastest
patchesStrategicMerge:
  - deployment-patch.yaml