apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: image-cache-demo
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
