apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: production
namePrefix: prod-
images:
- name: nginxdemos/hello
  newTag: "0.1"
patchesStrategicMerge:
  - deployment-patch.yaml