apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-cache-pv
  namespace: image-cache-demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nginx-cache

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cache-pvc
  namespace: image-cache-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-cache-pv
